-- ====================
-- DROPS
-- ====================

DROP TABLE IF EXISTS "user_resource" CASCADE;
DROP TABLE IF EXISTS "user_response" CASCADE;
DROP TABLE IF EXISTS "user_mission_attempt" CASCADE;
DROP TABLE IF EXISTS "user_mission" CASCADE;
DROP TABLE IF EXISTS "user_planet" CASCADE;
DROP TABLE IF EXISTS "user_achievement" CASCADE;
DROP TABLE IF EXISTS "user_stat" CASCADE;

DROP TABLE IF EXISTS "alternative" CASCADE;
DROP TABLE IF EXISTS "question" CASCADE;
DROP TABLE IF EXISTS "resource" CASCADE;
DROP TABLE IF EXISTS "achievement_target" CASCADE;
DROP TABLE IF EXISTS "achievement" CASCADE;

DROP TABLE IF EXISTS "mission" CASCADE;
DROP TABLE IF EXISTS "planet" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "level" CASCADE;

DROP DOMAIN IF EXISTS score CASCADE;
DROP DOMAIN IF EXISTS oxygen CASCADE;
DROP DOMAIN IF EXISTS xp CASCADE;

DROP TYPE IF EXISTS entity_type CASCADE;
DROP TYPE IF EXISTS achievement_type CASCADE;
DROP TYPE IF EXISTS achievement_scope CASCADE;
DROP TYPE IF EXISTS entity_status CASCADE;
DROP TYPE IF EXISTS mission_difficulty CASCADE;
DROP TYPE IF EXISTS planet_label CASCADE;
DROP TYPE IF EXISTS level_label CASCADE;



-- ====================
-- TYPES
-- ====================
CREATE TYPE level_label AS ENUM (
    'ALUMINIUM_I', 'ALUMINIUM_II', 'ALUMINIUM_III',
    
    'IRON_I', 'IRON_II', 'IRON_III',
    
    'NICKEL_I', 'NICKEL_II', 'NICKEL_III',
    
    'PALLADIUM_I', 'PALLADIUM_II', 'PALLADIUM_III'
);

CREATE TYPE planet_label AS ENUM (
    'VARIABILI', 
	'BIFURCA_9', 
	'CICLUS',
    'MATRX_0'
);

CREATE TYPE mission_difficulty
    AS ENUM (
        'EASY', 
        'MEDIUM', 
        'HARD'
        );

CREATE TYPE entity_status 
    AS ENUM (
        'LOCKED',
        'UNLOCKED', 
        'COMPLETED'
        );

CREATE TYPE achievement_scope 
    AS ENUM (
        'ENTITY', 
        'GAME'
        );

CREATE TYPE achievement_type
    AS ENUM (
        'UNLOCK', 
        'COMPLETED', 
        'COLLECTED'
        );

CREATE TYPE entity_type 
    AS ENUM (
        'LEVEL', 
        'MISSION', 
        'PLANET'
        );


-- ====================
-- DOMAINS
-- ====================

CREATE DOMAIN xp bigint CHECK (VALUE >= 0);
CREATE DOMAIN oxygen int CHECK (VALUE BETWEEN 0 AND 10);
CREATE DOMAIN score DECIMAL(5,2) CHECK (VALUE BETWEEN 0 AND 100);
CREATE DOMAIN progress DECIMAL(5,2) CHECK (VALUE BETWEEN 0 AND 100);


-- ====================
-- LEVEL
-- ====================

CREATE TABLE "level" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

	"name" level_label NOT NULL,
    "description" text,
    "order" int NOT NULL,
	
    "xp_required" xp NOT NULL,
	
	CONSTRAINT pk_level PRIMARY KEY (id),
	
    CONSTRAINT uk_level_number UNIQUE("name")
);

INSERT INTO "level" ("name", "description", "order", "xp_required") VALUES 
('ALUMINIUM_I',   NULL, 1, 0),
('ALUMINIUM_II',  NULL, 2, 250),
('ALUMINIUM_III', NULL, 3, 500);

INSERT INTO "level" ("name", "description", "order", "xp_required") VALUES 
('IRON_I',   NULL, 4, 1000),
('IRON_II',  NULL, 5, 1250),
('IRON_III', NULL, 6, 1500);

INSERT INTO "level" ("name", "description", "order", "xp_required") VALUES 
('NICKEL_I',   NULL, 7, 3000),
('NICKEL_II',  NULL, 8, 3250),
('NICKEL_III', NULL, 9, 3500); 

INSERT INTO "level" ("name", "description", "order", "xp_required") VALUES 
('PALLADIUM_I',   NULL, 10, 7000),
('PALLADIUM_II',  NULL, 11, 7250),
('PALLADIUM_III', NULL, 12, 7500);

-- ====================
-- USER
-- ====================

CREATE TABLE "user" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    "username" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
    "password" varchar(255) NOT NULL,

	level_id bigint NOT NULL DEFAULT 1,
    planet_id bigint NOT NULL DEFAULT 1,
    mission_id bigint NOT NULL DEFAULT 1,

	"xp" xp NOT NULL DEFAULT 0,
	"oxygen" oxygen NOT NULL DEFAULT 10,
	
    CONSTRAINT pk_user PRIMARY KEY (id),

	CONSTRAINT fk_user_level FOREIGN KEY (level_id) REFERENCES "level"(id),
	
    CONSTRAINT uk_user_email UNIQUE("email")
);


-- ====================
-- PLANET
-- ====================

CREATE TABLE "planet"(
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    "name" planet_label NOT NULL,
    "description" text,
    "order" int NOT NULL,

	"xp_bonus" xp NOT NULL,
	
    CONSTRAINT pk_planet PRIMARY KEY (id),
	
    CONSTRAINT uk_planet_name UNIQUE("name"),
    CONSTRAINT uk_planet_order UNIQUE("order")
);

ALTER TABLE "user" ADD CONSTRAINT fk_user_planet FOREIGN KEY (planet_id) REFERENCES "planet"(id);

INSERT INTO "planet" ("name", "description", "order", "xp_bonus") VALUES
('VARIABILI', NULL, 1, 100),
('BIFURCA_9', NULL, 2, 250),
('CICLUS',    NULL, 3, 500),
('MATRX_0',   NULL, 4, 1000);


CREATE TABLE "user_planet"(
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    user_id bigint NOT NULL,
    planet_id bigint NOT NULL,

	"status" entity_status NOT NULL DEFAULT 'LOCKED',
    "is_accessible" boolean NOT NULL DEFAULT false,
    "progress" progress NOT NULL DEFAULT 0,
	
    CONSTRAINT pk_user_planet PRIMARY KEY (id),

    CONSTRAINT fk_user_planet_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_planet_planet FOREIGN KEY (planet_id) REFERENCES "planet"(id) ON DELETE CASCADE,

    CONSTRAINT uk_user_planet UNIQUE (user_id, planet_id)
);

-- ====================
-- MISSION
-- ====================

CREATE TABLE "mission" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    planet_id bigint NOT NULL,

    "name" varchar(255) NOT NULL,
    "description" text,
    "order" int NOT NULL,

    "difficulty" mission_difficulty NOT NULL,
	"xp_bonus" xp NOT NULL,
	
    CONSTRAINT pk_mission PRIMARY KEY (id),

    CONSTRAINT fk_mission_planet FOREIGN KEY(planet_id) REFERENCES "planet"(id) ON DELETE CASCADE,

    CONSTRAINT uk_mission_planet_name UNIQUE(planet_id, "name"),
    CONSTRAINT uk_mission_planet_order UNIQUE (planet_id, "order")
);

ALTER TABLE "user" ADD CONSTRAINT fk_user_mission FOREIGN KEY (mission_id) REFERENCES "mission"(id);

INSERT INTO "mission" (planet_id, "name", "description", "order", "difficulty", "xp_bonus") VALUES
(1, 'Planet - 1 : Mission - 1 ', NULL, 1, 'EASY', 100),
(1, 'Planet - 1 : Mission - 2 ', NULL, 2, 'MEDIUM', 100),
(1, 'Planet - 1 : Mission - 3 ', NULL, 3, 'HARD', 100),
(2, 'Planet - 2 : Mission - 1 ', NULL, 1, 'EASY', 100),
(2, 'Planet - 2 : Mission - 2 ', NULL, 2, 'MEDIUM', 100),
(2, 'Planet - 2 : Mission - 3 ', NULL, 3, 'HARD', 100),
(3, 'Planet - 3 : Mission - 1 ', NULL, 1, 'EASY', 100),
(3, 'Planet - 3 : Mission - 2 ', NULL, 2, 'MEDIUM', 100),
(3, 'Planet - 3 : Mission - 3 ', NULL, 3, 'HARD', 100),
(4, 'Planet - 4 : Mission - 1 ', NULL, 1, 'EASY', 100),
(4, 'Planet - 4 : Mission - 2 ', NULL, 2, 'MEDIUM', 100),
(4, 'Planet - 4 : Mission - 3 ', NULL, 3, 'HARD', 100);

CREATE TABLE "user_mission" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    user_id bigint NOT NULL,
    mission_id bigint NOT NULL,

    "status" entity_status NOT NULL DEFAULT 'LOCKED',
    "is_accessible" boolean NOT NULL DEFAULT false,
    "best_result" score NOT NULL DEFAULT 0,
    "progress" progress NOT NULL DEFAULT 0,
	
    CONSTRAINT pk_user_mission PRIMARY KEY(id),
	
    CONSTRAINT fk_user_mission_user FOREIGN KEY(user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_mission_mission FOREIGN KEY(mission_id) REFERENCES "mission"(id) ON DELETE CASCADE,

    CONSTRAINT uk_user_mission UNIQUE (user_id, mission_id)
);

CREATE TABLE "user_mission_attempt" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    user_mission_id bigint NOT NULL,

    "start_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "end_at" timestamp,
    "result" score NOT NULL DEFAULT 0,

    CONSTRAINT pk_attempt PRIMARY KEY(id),

    CONSTRAINT fk_attempt_user_mission FOREIGN KEY (user_mission_id) REFERENCES "user_mission"(id) ON DELETE CASCADE,

    CONSTRAINT ck_user_mission_attempt CHECK ("end_at" >= "start_at")
);


-- ====================
-- QUESTION
-- ====================

CREATE TABLE "question" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    mission_id bigint NOT NULL,

    "description" text NOT NULL,
    "code_snippet" text NOT NULL,
    "order" int NOT NULL,
	
    CONSTRAINT pk_question PRIMARY KEY (id),
	
    CONSTRAINT fk_question_mission FOREIGN KEY(mission_id) REFERENCES "mission"(id) ON DELETE CASCADE,

    CONSTRAINT uk_question_mission_order UNIQUE (mission_id, "order")
);

CREATE TABLE "alternative" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    question_id bigint NOT NULL,

    "content" text NOT NULL,
    "feedback_tip" text NOT NULL,
    "is_correct" boolean NOT NULL DEFAULT false,
	
    CONSTRAINT pk_alternative PRIMARY KEY(id),

    CONSTRAINT fk_alternative_question FOREIGN KEY (question_id) REFERENCES "question"(id) ON DELETE CASCADE,

	CONSTRAINT uk_alternative_content UNIQUE(question_id, "content"),
    CONSTRAINT uk_alternative UNIQUE (question_id, id)
);

CREATE TABLE "user_response" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    
    attempt_id bigint NOT NULL,
    question_id bigint NOT NULL,
    alternative_id bigint NOT NULL,
	
    CONSTRAINT pk_user_response PRIMARY KEY(id),
	
    CONSTRAINT fk_user_response_attempt
        FOREIGN KEY (attempt_id)
        REFERENCES "user_mission_attempt"(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_user_response_question
        FOREIGN KEY (question_id)
        REFERENCES "question"(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_user_response_alternative
        FOREIGN KEY (question_id, alternative_id)
        REFERENCES "alternative"(question_id, id)
        ON DELETE CASCADE,

    CONSTRAINT uk_user_response_question
        UNIQUE(attempt_id, question_id)
);


-- ====================
-- RESOURCE
-- ====================

CREATE TABLE "resource" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    planet_id bigint NOT NULL,

    "name" varchar(255) NOT NULL,
    "description" text,

    "xp_bonus" xp NOT NULL,
	
    CONSTRAINT pk_resource PRIMARY KEY (id),
	
    CONSTRAINT fk_resource_planet FOREIGN KEY(planet_id) REFERENCES "planet"(id) ON DELETE CASCADE,

    CONSTRAINT uk_resource_planet UNIQUE (planet_id),
    CONSTRAINT uk_resource_name UNIQUE ("name")
);

INSERT INTO "resource" (planet_id, "name", "description", "xp_bonus") VALUES
(1, 'Planet - 1 : Resource', NULL, 100),
(2, 'Planet - 2 : Resource', NULL, 100),
(3, 'Planet - 3 : Resource', NULL, 100),
(4, 'Planet - 4 : Resource', NULL, 100);

CREATE TABLE "user_resource" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    user_id bigint NOT NULL,
    resource_id bigint NOT NULL,

    "is_collected" boolean DEFAULT false,
    "collected_at" timestamp,
	
    CONSTRAINT pk_user_resource PRIMARY KEY(id),
	
    CONSTRAINT fk_user_resource_user FOREIGN KEY(user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_resource_resource FOREIGN KEY(resource_id) REFERENCES "resource"(id) ON DELETE CASCADE,

    CONSTRAINT uk_user_resource UNIQUE (user_id, resource_id)
);


-- ====================
-- ACHIEVEMENT
-- ====================

CREATE TABLE "achievement" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    "name" varchar(255) NOT NULL,
    "description" text,
    "type" achievement_type NOT NULL,
    "scope" achievement_scope NOT NULL,
    "bonus_xp" int NOT NULL DEFAULT 0,
    
    CONSTRAINT pk_achievement PRIMARY KEY(id),

    CONSTRAINT ck_achievement_bonus_xp CHECK (bonus_xp >= 0)
);

CREATE TABLE "achievement_target" (
    achievement_id bigint NOT NULL,
    entity_id bigint NOT NULL,
    
    "entity" entity_type NOT NULL,
    
    CONSTRAINT pk_achievement_target PRIMARY KEY (achievement_id, entity, entity_id),

    CONSTRAINT fk_achievement_target_achievement FOREIGN KEY(achievement_id) REFERENCES "achievement"(id) ON DELETE CASCADE
);

CREATE TABLE "user_achievement" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    user_id bigint NOT NULL,
    achievement_id bigint NOT NULL,

    "collected_at" timestamp DEFAULT CURRENT_TIMESTAMP,
	
    CONSTRAINT pk_user_achievement PRIMARY KEY(id),
	
    CONSTRAINT fk_user_achievement_user FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_achievement_achievement FOREIGN KEY (achievement_id) REFERENCES "achievement"(id) ON DELETE CASCADE,

    CONSTRAINT uk_user_achievement_pair UNIQUE (user_id, achievement_id)
);
